# Base images with R and RStudio pre-installed 
FROM rocker/rstudio:4.3.1

# Set Environment variables
ENV PASSWORD=abc123
ENV R_LIBS_USER=/home/rstudio/R

# Create a direcotry and give rstudio user permission
RUN mkdir -p $R_LIBS_USER && chown -R rstudio:rstudio $R_LIBS_USER

# Install required linux libraries and depdnencies
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxt-dev \
    libcairo2-dev \
    libxml2-dev \
    libfftw3-dev \
    libx11-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libgit2-dev \
    zlib1g-dev \
    libglpk-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Copy my package installation script
COPY install_packages.R /tmp/install_packages.R

# Run package installation script 
Run Rscript /tmp/install_packages.R
